name: Test and Lint

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test_lint:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7, 3.8]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        poetry config virtualenvs.in-project true
        poetry install -E mne
    - name: Testing
      run: |
        poetry run doit test
        poetry run coverage-badge -o coverage-badge.svg
    - name: Commit Coverage Badge
      run: |
        git config --global user.name 'Coverage Badge'
        git config --global user.email 'coverage-badge@users.noreply.github.com'
        git add coverage-badge.svg
        git commit -m "Added Coverage Badge"
        git push
    - name: Linting
      run: |
        poetry run doit -v 0 --continue format_check lint
#    - name: Publish Coverage Badge
#      uses: actions/upload-artifact@v2
#      with:
#        name: coverage-badge
#        path: coverage-badge.svg

